### ISSUE TITLE
roles/ doesn't exist

### ISSUE THREAD

**Issue by chezbut** [hectcastro/vagrant-netflix-ice#1]
Where does roles/hectcastro.ice come from and how is it supposed to be generated? 
Wondering that. 

==> default: Running provisioner: ansible...
ERROR: cannot find role in /home/zhanna/icetest/roles/hectcastro.ice or /home/zhanna/icetest/hectcastro.ice or /etc/ansible/roles/hectcastro.ice
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by hectcastro** [comment]
The Ice role can be installed via [`ansible-galaxy`](https://galaxy.ansible.com/list#/roles/1665) or cloned directly from [GitHub](https://github.com/hectcastro/ansible-ice).
